### PR TITLE
Fix C++ parsing bugs

### LINKED ISSUE #234: Body of method comment is not autogenerated if return type is template (C++)
In C++, if you type /** at the beginning of a method and then hit enter, the body of the comment section is autogenereated, including parameter names and return statement.

If the return type of the function is templated (for instance, std::vector<int>), however, no body is autogenerated.

### PR DESCRIPTION
**Pull request by audreyseo**
Fixed #234 and #273 and also added specs. The specs cover these bugs as well as other basic functionality of parsing C++ code.

### CODE REVIEW

File: lib/languages/cpp.js [hunk 1]
```diff
@@ -36,11 +36,19 @@ CppParser.prototype.parse_function = function(line) {
...
+      var reg = xregexp('(?P<name>' + this.settings.fnIdentifier + ')' + '\\s*\\(\\s*(?P<args>.*?)\\)');
+      matches = xregexp.exec(line, reg);
+      if (matches === null) {
         return null;
+      }
     }
 
-    return [matches.name, matches.args, matches.retval];
+    var args = matches.args || null
+    retval = matches.retval || null
```
Comment (MoritzKn) [inline lib/languages/cpp.js]: Please move the declaration of retval down to its first assignment. As far as I can see it's not used before.

File: lib/languages/cpp.js [hunk 2]
```diff
@@ -36,11 +36,19 @@ CppParser.prototype.parse_function = function(line) {
     );
 
     var matches = xregexp.exec(line, regex);
+    var retval;
     if(matches === null) {
+      var reg = xregexp('(?P<name>' + this.settings.fnIdentifier + ')' + '\\s*\\(\\s*(?P<args>.*?)\\)');
```
Comment (MoritzKn) [inline lib/languages/cpp.js]: Could you explain why you choose to have an alternative regex for constructors? It seems like it would have been possible to alter the existing regex as well.

**Comment by MoritzKn** [comment]
@audreyseo thanks for the explanation, but while testing I could spot a problem with that:

If there is only a constructor everything works fine:
```c++
/**
 * [Foo description]
 * @param bar [description]
 */
Foo(bar) {
}
```
But if the constructor is followed by a method it matches the method and ignores the constructor:
```c++
/**
 * [test description]
 * @returns [description]
 */
Foo(bar) {
}

vod test() {
    
}
```

**Comment by MoritzKn** [comment]
Great, thanks again! I'm going to create a new release.
